version: '3'
services:
  backend:
    build: .
    container_name: backend
    restart: on-failure
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - shared_network
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - shared_network
volumes:
  redis_data:
    driver: 'local'
networks:
  shared_network:
    driver: bridge